# Site settings
title: "Jekyll Resume Template"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "false"
resume_name:                    "Vineet G Kowti"
resume_title:                   "About Me"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "vineetgkowti@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "555-7334"
resume_contact_address:         "742 Evergreen Terrace, Springfield"

resume_header_contact_info:     "742 Evergreen Terrace, Springfield • 555-7334 • lisasimpson@youremailaddress.com"
display_header_contact_info:    "true"

resume_header_intro: "<p>I am senior student at Jawaharlal Nehru National College of Engineering, Shivamogga, majoring in Computer
Science. I am passionate about using technology to solve complex problems and improve people's lives. I am
always eager to learn new technologies and programming techniques . I thrive in team-oriented environments
and enjoy collaborating with others to achieve common goals. I am excited to bring my skills and enthusiasm for
computer science to a challenging and rewarding role in the tech industry</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/VineetGK"
  #resume_twitter_url:           "http://twitter.com/jglovier"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          ""https://www.linkedin.com/in/vineetgkowti
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://vineetgk.github.io/res/"
  #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
